[package]
name = "localcv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bytes = "1.8.0"
futures = "0.3.31"
srt-tokio = "0.4.4"
tokio = { version = "1", features = ["full"] }
video-rs = "0.10.2"
