[package]
name = "localcv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
csv = "1.3.1"
opencv = "0.93.4"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
cmake = "0.1.31"
